title: "Adithya Framilton"
description: "Minimal, focused documentation of my learning, building, and creating."
baseurl: ""
url: "https://ashwalkerexe.github.io"
theme: jekyll-theme-minimal

author: Adithya Framilton

# Optional: Clean nav bar links
logo: /assets/profile.png
show_downloads: false
