title: "Adithya Ashwin"
description: "Learning in public. Linux. CS50. OBS. Dotfiles."
baseurl: "" # Do not change
url: "https://ashwalkerexe.github.io"
theme: jekyll-theme-minimal
include:
  - head.html
